server:
    port: 8881


spring:
    cloud:
        gateway:
            default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
              corsConfigurations:
                '[/**]':
                    allowedOrigins: "*"
                    allowedMethods: "*"
                    allowedHeaders: "*"
            routes:
            - id: UserDetails-Microservice
              uri: http://54.88.205.130:8082
              predicates:
              - Path= /users/**
            - id: Book-service
              uri: http://23.21.10.104:5050
              predicates:
              - Path= /books/**
            - id: Whislist-service
              uri: http://184.73.7.4:8083 
              predicates:
              - Path= /fav/**
            - id: Authorization
              uri: http://54.88.205.130:8000
              predicates:
              - Path= /auth/**
            
    application:
        name: API-GATEWAY-SERVICE          

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://174.129.184.236:8761/eureka/
    instance:
        hostname: aditieureka
